/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{vue,ts}'],
  theme: {
    extend: {
      colors: {
        bg: '#ffffff',
        'bg-alt': '#f3f4ef',
        surface: '#eeefe9',
        'bg-dark': '#1d1f27',
        'surface-dark': '#2c2e36',
        text: '#000000',
        'text-muted': '#5f5e5b',
        'text-dim': '#8a8980',
        border: '#d0d1c9',
        'border-strong': '#b6b6ad',
        accent: '#1d4aff',
        'accent-hover': '#1639cc',
        warning: '#f9bd2b',
        success: '#29dbbb',
        danger: '#db3707',
        chart: {
          1: '#1d4aff',
          2: '#f9bd2b',
          3: '#29dbbb',
          4: '#db3707',
          5: '#621da6',
          6: '#ff9d3a',
          7: '#36a2eb',
          8: '#6a3700',
        },
      },
      fontFamily: {
        sans: ['Matter', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['Matter Mono', 'JetBrains Mono', 'monospace'],
      },
      fontSize: {
        '2xs': '11px',
        xs: '12px',
        sm: '13px',
        base: '14px',
        md: '16px',
        lg: '18px',
        xl: '22px',
        '2xl': '28px',
        '3xl': '36px',
        '4xl': '48px',
      },
      borderRadius: {
        DEFAULT: '6px',
        md: '6px',
        lg: '8px',
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '6': '24px',
        '8': '32px',
        '12': '48px',
      },
      boxShadow: {
        modal: '0 8px 24px rgba(0,0,0,0.12)',
      },
      maxWidth: {
        app: '1440px',
      },
    },
  },
  plugins: [],
}
